### ISSUE TITLE
IOError when opening the file specified in WriteROptions results in stack trace and exiting

### ISSUE THREAD

**Issue by marshallflax** [ajrgodfrey/WriteR#15]
We should catch the IOException (which could occur, for instance, if the drive mentioned in the WriteROptions isn't mounted, etc) and do something reasonable.  Perhaps even just put up a modal dialogue with the details and instructions as to what to do -- and then exit gracefully.

**Comment by ajrgodfrey** [comment]
OK. Sounds good. Probably other instances where this approach is warranted.

**Comment by marshallflax** [comment]
#16 handles this IOError upon opening files and when invoking RScript. If there are other cases in which you've seen errors, we can do similar try/catch blocks as well (but most errors aren't grounds for simply throwing up a dialog and then exiting, of course).
