### ISSUE TITLE
Find/Replace function can be learned from this demo

### ISSUE THREAD

**Issue by jooyoungseo** [ajrgodfrey/WriteR#4]
Hello,

As far as know, the current find and replace function is broken in WriteR.

I have obtained a demo wxPython source code for Find and Replace that is retrieved from https://github.com/wxWidgets/wxPython/tree/master/demo

Please find the attached and see if you can implement this code.

Thank you very much.
[FindReplaceDialog.py.txt](https://github.com/ajrgodfrey/WriteR/files/1835938/FindReplaceDialog.py.txt)

**Comment by ajrgodfrey** [comment]
Not broken, but more accurately, not implemented. I put a placeholder in the menus as I thought  the solution was within reach. It hasn’t proven so for me at this stage.
Any code suggestions are welcome.

**Comment by marshallflax** [comment]
Search and replace-all addressed in https://github.com/ajrgodfrey/WriteR/pull/7

**Comment by ajrgodfrey** [comment]
workr in PR7 delivers on tis issue. My thanks to @marshallflax for his contributions.
