### ISSUE TITLE
Somehow integrate https://cran.r-project.org/package=sonify ?

### ISSUE THREAD

**Issue by marshallflax** [ajrgodfrey/WriteR#8]
I just heard of the sonify package ... does it make sense to try to integrate into WriteR somehow?  What would such integration look like?  Perhaps an <audio> element in the HTML output? Would such a thing be something that WriteR would help with, or is it something that would have to be done within rmarkdown::render()?

**Comment by ajrgodfrey** [comment]
Not really sensible to put it into WriteR.

There is scope for it to fit into the BrailleR framework though, although it would be referred to as against being duplicated inside BrailleR. There is still plenty of work to do with sonification, and the package probably needs some improvements around using methods and separate functionality for different classes.

Suggest closure.
Jonathan

**Comment by marshallflax** [comment]
Clearly I need to investigate the BrailleR package more!  Thanks!
